pub mod ai;
mod command_registry;
pub mod crash_report;
pub mod db;
pub mod extensions;
pub mod git;
pub mod indexing;
pub mod jobs;
pub mod pty;
pub mod security;

/// Install the TLS backend before anything can build an HTTPS client.
///
/// reqwest is compiled without a default crypto provider so the binary does not
/// carry a second C crypto stack beside the ring that tauri-plugin-updater
/// needs. That makes reqwest's `default_rustls_crypto_provider()` a `panic!`
/// until a provider is installed, and the db connectors, the extension store,
/// and the updater plugin all build clients independently of irodori-generate,
/// so installing it inside that crate is not enough. Ignoring the `Err` is
/// deliberate: it only reports that a provider was already installed.
fn install_crypto_provider() {
    let _ = rustls::crypto::ring::default_provider().install_default();
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    install_crypto_provider();

    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init());
    #[cfg(feature = "updater")]
    let builder = builder.plugin(tauri_plugin_updater::Builder::new().build());

    builder
        .manage(db::DbState::default())
        .manage(extensions::ExtensionsState::default())
        .manage(jobs::JobState::default())
        .manage(indexing::SchemaIndexState::default())
        .manage(security::SecurityState::default())
        .manage(ai::AiState::default())
        .manage(pty::PtyState::default())
        .setup(|app| {
            // Restore the persisted AI provider (selection + keychain API key) so
            // the user doesn't reconfigure it on every launch.
            use tauri::Manager;
            let handle = app.handle().clone();
            app.manage(crash_report::initialize(&handle));
            let ai = app.state::<ai::AiState>();
            let security = app.state::<security::SecurityState>();
            ai::hydrate_provider(&handle, &ai, &security);
            Ok(())
        })
        .invoke_handler(command_registry::invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod typegen {
    use super::*;
    use std::fs;
    use std::path::Path;
    use typeship::ir::{Decl, TsType};
    use typeship::{Arg, Bridge, Command};
    use typeship_ts_rs::decl;

    const GENERATED: &str = "../src/generated/irodori-api.ts";

    fn normalized_bindings(contents: &str) -> String {
        let mut normalized = contents
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n");
        normalized.push('\n');
        normalized
    }

    /// The single source of truth for the desktop TypeScript boundary.
    ///
    /// Each Rust type is rendered by ts-rs via [`decl`]; `typeship` assembles the
    /// module header, the typed Tauri command wrappers, and (in CI) the drift
    /// check. `JsonValue` is a hand-declared alias because `serde_json::Value`
    /// renders to a bare `JsonValue` reference under ts-rs's `serde-json-impl`.
    fn bridge() -> Bridge {
        Bridge::tauri()
            .header("// @generated by cargo test export_typescript_bindings. Do not edit.")
            .decl(&Decl::alias("JsonValue", TsType::unknown()))
            .decl(&decl::<irodori_error::IrodoriErrorKind>())
            .decl(&decl::<irodori_error::IrodoriError>())
            .decl(&decl::<irodori_error::CommandResult<serde_json::Value>>())
            .decl(&decl::<irodori_jobs::JobKind>())
            .decl(&decl::<irodori_jobs::JobStatus>())
            .decl(&decl::<irodori_jobs::JobLogLevel>())
            .decl(&decl::<irodori_jobs::JobRetryPolicy>())
            .decl(&decl::<irodori_jobs::JobConcurrencyPolicy>())
            .decl(&decl::<irodori_jobs::JobResourceBudget>())
            .decl(&decl::<irodori_jobs::JobSpec>())
            .decl(&decl::<irodori_jobs::JobProgress>())
            .decl(&decl::<irodori_jobs::JobCheckpoint>())
            .decl(&decl::<irodori_jobs::JobArtifact>())
            .decl(&decl::<irodori_jobs::JobLogEntry>())
            .decl(&decl::<irodori_jobs::JobRecord>())
            .decl(&decl::<irodori_jobs::JobSummary>())
            .decl(&decl::<irodori_jobs::JobList>())
            .decl(&decl::<irodori_jobs::JobRuntimeConfig>())
            .decl(&decl::<irodori_security::PrivacyMode>())
            .decl(&decl::<irodori_security::RedactionReport>())
            .decl(&decl::<irodori_security::RedactedExport>())
            .decl(&decl::<irodori_connection::SecretRef>())
            .decl(&decl::<irodori_connection::JwtAlgorithm>())
            .decl(&decl::<irodori_connection::OAuth2Flow>())
            .decl(&decl::<irodori_connection::AwsAuthSource>())
            .decl(&decl::<irodori_connection::GcpAuthSource>())
            .decl(&decl::<irodori_connection::AzureAuthSource>())
            .decl(&decl::<irodori_connection::AuthConfig>())
            .decl(&decl::<irodori_connection::TlsMode>())
            .decl(&decl::<irodori_connection::TlsConfig>())
            .decl(&decl::<irodori_connection::TransportConfig>())
            .decl(&decl::<irodori_connection::DirectTransport>())
            .decl(&decl::<irodori_connection::LocalFileTransport>())
            .decl(&decl::<irodori_connection::SshTunnelTransport>())
            .decl(&decl::<irodori_connection::SshAuthConfig>())
            .decl(&decl::<irodori_connection::ProxyTransport>())
            .decl(&decl::<irodori_connection::ProxyAuthConfig>())
            .decl(&decl::<irodori_connection::ProxyChainTransport>())
            .decl(&decl::<irodori_connection::ProxyChainHop>())
            .decl(&decl::<irodori_connection::ProxyHopConfig>())
            .decl(&decl::<irodori_connection::SshProxyHop>())
            .decl(&decl::<irodori_proxy::DialTarget>())
            .decl(&decl::<irodori_proxy::TransportStepKind>())
            .decl(&decl::<irodori_proxy::TransportStep>())
            .decl(&decl::<irodori_proxy::TransportPlan>())
            .decl(&decl::<irodori_proxy::DiagnosticStageKind>())
            .decl(&decl::<irodori_proxy::DiagnosticStatus>())
            .decl(&decl::<irodori_proxy::DiagnosticStage>())
            .decl(&decl::<irodori_proxy::ConnectionDiagnostics>())
            .decl(&decl::<security::DesktopSecretPurpose>())
            .decl(&decl::<ai::AiGenerateResult>())
            .decl(&decl::<ai::AiEngineStatus>())
            .decl(&decl::<ai::AiProviderKind>())
            .decl(&decl::<ai::AiProviderConfig>())
            .decl(&decl::<command_registry::DbObjectKind>())
            .decl(&decl::<command_registry::ConnectionStatus>())
            .decl(&decl::<command_registry::DbObject>())
            .decl(&decl::<command_registry::Connection>())
            .decl(&decl::<command_registry::WorkspaceSnapshot>())
            .decl(&decl::<crash_report::CrashReportStatus>())
            .decl(&decl::<db::DbEngine>())
            .decl(&decl::<db::EngineBuildSupport>())
            .decl(&decl::<db::ConnectionProfile>())
            .decl(&decl::<db::ConnectionInfo>())
            .decl(&decl::<db::QueryResultSet>())
            .decl(&decl::<db::QueryResult>())
            .decl(&decl::<db::SpillRunResult>())
            .decl(&decl::<db::ResultWindow>())
            .decl(&decl::<db::QueryParameterKey>())
            .decl(&decl::<db::QueryParameterInput>())
            .decl(&decl::<db::QueryParameterPrompt>())
            .decl(&decl::<db::QueryParameterPromptSet>())
            .decl(&decl::<db::QueryPlanMode>())
            .decl(&decl::<db::QueryPlanSource>())
            .decl(&decl::<db::QueryPlanSeverity>())
            .decl(&decl::<db::QueryPlanProperty>())
            .decl(&decl::<db::QueryPlanNode>())
            .decl(&decl::<db::QueryPlanEdge>())
            .decl(&decl::<db::QueryPlanFlameFrame>())
            .decl(&decl::<db::QueryPlanMetric>())
            .decl(&decl::<db::QueryPlanFinding>())
            .decl(&decl::<db::QueryPlanMetricGuide>())
            .decl(&decl::<db::QueryPlanCopyFormat>())
            .decl(&decl::<db::QueryPlanAnalysis>())
            .decl(&decl::<db::DatabaseMetadata>())
            .decl(&decl::<db::SchemaMetadata>())
            .decl(&decl::<db::ForeignKey>())
            .decl(&decl::<db::DbQuickSample>())
            .decl(&decl::<db::DbObjectMetadata>())
            .decl(&decl::<db::DbObjectMetadataKind>())
            .decl(&decl::<db::ColumnMetadata>())
            .decl(&decl::<db::IndexMetadata>())
            .decl(&decl::<db::CellValue>())
            .decl(&decl::<db::RowUpdate>())
            .decl(&decl::<db::RowInsert>())
            .decl(&decl::<db::RowDelete>())
            .decl(&decl::<db::TableEdits>())
            .decl(&decl::<db::AppliedEdits>())
            .decl(&decl::<db::MigrationPlanExportFormat>())
            .decl(&decl::<db::MigrationPlanInput>())
            .decl(&decl::<db::MigrationPlanTaskLevel>())
            .decl(&decl::<db::MigrationPlanTask>())
            .decl(&decl::<db::MigrationPlanOutput>())
            .decl(&decl::<db::DbCompletionItem>())
            .decl(&decl::<db::DbCompletionItemKind>())
            .decl(&decl::<db::DbInspectionCard>())
            .decl(&decl::<db::DbObjectInspection>())
            .decl(&decl::<db::DbColumnInspection>())
            .decl(&decl::<db::DbColumnReference>())
            .decl(&decl::<extensions::InstalledExtension>())
            .decl(&decl::<extensions::ExtensionInstallKind>())
            .decl(&decl::<extensions::ExtensionInstallRequest>())
            .decl(&decl::<indexing::SchemaSearchHit>())
            .decl(&decl::<git::GitChangeKind>())
            .decl(&decl::<git::GitRemoteProvider>())
            .decl(&decl::<git::GitFileStatus>())
            .decl(&decl::<git::GitCommitSummary>())
            .decl(&decl::<git::GitRemoteSummary>())
            .decl(&decl::<git::GitBranchSummary>())
            .decl(&decl::<git::GitStatusSummary>())
            .decl(&decl::<git::GitDiffResult>())
            .decl(&decl::<git::GitCommandOutput>())
            .command(Command::new("workspace_snapshot", "WorkspaceSnapshot"))
            .command(Command::returning("open_developer_tools", TsType::void()))
            .command(Command::new("crash_report_status", "CrashReportStatus"))
            .command(
                Command::new("sql_format_snowflake", "string")
                    .arg(Arg::new("sql", TsType::string()))
                    .arg(Arg::rust("line_width", TsType::number()).optional())
                    .arg(Arg::rust("indent_width", TsType::number()).optional())
                    .arg(Arg::rust("uppercase_keywords", TsType::boolean()).optional()),
            )
            .command(Command::new("jobs_list", "JobList"))
            .command(
                Command::new("jobs_get", "JobRecord | null")
                    .arg(Arg::rust("job_id", TsType::string())),
            )
            .command(
                Command::returning("jobs_cancel", TsType::boolean())
                    .arg(Arg::rust("job_id", TsType::string())),
            )
            .command(
                Command::new("db_search_schema", "Array<SchemaSearchHit>")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("term", TsType::string()))
                    .arg(Arg::rust("limit", TsType::number()).optional()),
            )
            .command(Command::new(
                "db_engine_build_support",
                "Array<EngineBuildSupport>",
            ))
            .command(Command::new("db_connect", "ConnectionInfo").arg(Arg::new(
                "profile",
                TsType::named("ConnectionProfile<DbEngine>"),
            )))
            .command(
                Command::new("db_query_parameters", "QueryParameterPromptSet")
                    .arg(Arg::new("sql", TsType::string())),
            )
            .command(
                Command::new("db_explain_query", "QueryPlanAnalysis")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("sql", TsType::string()))
                    .arg(Arg::new("mode", TsType::named("QueryPlanMode"))),
            )
            .command(
                Command::new("db_run_query", "QueryResult")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("sql", TsType::string()))
                    .arg(Arg::rust("max_rows", TsType::number()).optional())
                    .arg(Arg::rust("timeout_ms", TsType::number()).optional())
                    .arg(Arg::rust("query_id", TsType::string()).optional())
                    .arg(
                        Arg::new("params", TsType::named("Array<QueryParameterInput>")).optional(),
                    ),
            )
            .command(
                Command::returning("db_cancel", TsType::boolean())
                    .arg(Arg::rust("query_id", TsType::string())),
            )
            // `db_run_query_spill` takes a streaming `Channel`, so (like
            // `db_run_query_stream`) its wrapper is hand-written in `db-stream.ts`;
            // only its read/release companions are generated here. The
            // `SpillRunResult` / `ResultWindow` types are declared above so the
            // hand-written wrapper stays typed.
            .command(
                Command::new("db_result_window", "ResultWindow")
                    .arg(Arg::new("handle", TsType::string()))
                    .arg(Arg::new("offset", TsType::number()))
                    .arg(Arg::new("limit", TsType::number())),
            )
            .command(
                Command::returning("db_release_result", TsType::boolean())
                    .arg(Arg::new("handle", TsType::string())),
            )
            .command(
                Command::new("db_apply_edits", "AppliedEdits")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("edits", TsType::named("TableEdits"))),
            )
            .command(
                Command::new("migration_build_plan", "MigrationPlanOutput")
                    .arg(Arg::new("input", TsType::named("MigrationPlanInput"))),
            )
            .command(
                Command::new("db_list_objects", "DatabaseMetadata")
                    .arg(Arg::rust("connection_id", TsType::string())),
            )
            .command(
                Command::returning("db_disconnect", TsType::void())
                    .arg(Arg::rust("connection_id", TsType::string())),
            )
            .command(
                Command::new("db_autocomplete", "Array<DbCompletionItem>")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("prefix", TsType::string()))
                    .arg(Arg::rust("schema", TsType::string()).optional())
                    .arg(Arg::rust("object", TsType::string()).optional())
                    .arg(Arg::rust("limit", TsType::number()).optional()),
            )
            .command(
                Command::new("db_inspect_object", "DbInspectionCard | null")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("schema", TsType::string()))
                    .arg(Arg::new("object", TsType::string())),
            )
            .command(
                Command::new("db_inspect_column", "DbInspectionCard | null")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("schema", TsType::string()))
                    .arg(Arg::new("object", TsType::string()))
                    .arg(Arg::new("column", TsType::string())),
            )
            .command(
                Command::returning("db_invalidate_cache", TsType::boolean())
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::rust("schema", TsType::string()).optional())
                    .arg(Arg::rust("object", TsType::string()).optional()),
            )
            .command(Command::new("ext_list", "Array<InstalledExtension>"))
            .command(Command::new("ext_target", "string"))
            .command(
                Command::new("ext_install", "InstalledExtension").arg(Arg::new(
                    "request",
                    TsType::named("ExtensionInstallRequest"),
                )),
            )
            .command(
                Command::returning("ext_uninstall", TsType::boolean())
                    .arg(Arg::new("id", TsType::string())),
            )
            .command(
                Command::new("ext_set_enabled", "InstalledExtension")
                    .arg(Arg::new("id", TsType::string()))
                    .arg(Arg::new("enabled", TsType::boolean())),
            )
            .command(
                Command::new("git_status", "GitStatusSummary")
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_log", "Array<GitCommitSummary>")
                    .arg(Arg::rust("repo_path", TsType::string()).optional())
                    .arg(Arg::new("limit", TsType::number()).optional()),
            )
            .command(
                Command::new("git_diff", "GitDiffResult")
                    .arg(Arg::rust("repo_path", TsType::string()).optional())
                    .arg(Arg::rust("file_path", TsType::string()).optional())
                    .arg(Arg::new("commit", TsType::string()).optional()),
            )
            .command(
                Command::new("git_commit_all", "GitCommandOutput")
                    .arg(Arg::new("message", TsType::string()))
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_commit_staged", "GitCommandOutput")
                    .arg(Arg::new("message", TsType::string()))
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_push", "GitCommandOutput")
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_fetch", "GitCommandOutput")
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_pull", "GitCommandOutput")
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_stage_files", "GitCommandOutput")
                    .arg(Arg::new("paths", TsType::named("Array<string>")))
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_unstage_files", "GitCommandOutput")
                    .arg(Arg::new("paths", TsType::named("Array<string>")))
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_discard_files", "GitCommandOutput")
                    .arg(Arg::new("paths", TsType::named("Array<string>")))
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(
                Command::new("git_checkout_branch", "GitCommandOutput")
                    .arg(Arg::new("branch", TsType::string()))
                    .arg(Arg::new("create", TsType::boolean()).optional())
                    .arg(Arg::rust("repo_path", TsType::string()).optional())
                    .arg(Arg::rust("start_point", TsType::string()).optional()),
            )
            .command(
                Command::new("git_delete_branch", "GitCommandOutput")
                    .arg(Arg::new("branch", TsType::string()))
                    .arg(Arg::new("force", TsType::boolean()).optional())
                    .arg(Arg::rust("repo_path", TsType::string()).optional()),
            )
            .command(Command::new("security_get_privacy_mode", "PrivacyMode"))
            .command(
                Command::new("security_set_privacy_mode", "PrivacyMode")
                    .arg(Arg::new("mode", TsType::named("PrivacyMode"))),
            )
            .command(
                Command::new("security_redact_text", "RedactionReport")
                    .arg(Arg::new("text", TsType::string())),
            )
            .command(Command::new("security_export_audit", "RedactedExport"))
            .command(
                Command::new("security_store_secret", "SecretRef")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("purpose", TsType::named("DesktopSecretPurpose")))
                    .arg(Arg::new("value", TsType::string())),
            )
            .command(
                Command::returning("security_delete_secret", TsType::void())
                    .arg(Arg::new("secret", TsType::named("SecretRef"))),
            )
            .command(
                Command::new("network_transport_plan", "TransportPlan")
                    .arg(Arg::new("transport", TsType::named("TransportConfig"))),
            )
            .command(
                Command::new("network_diagnose_transport", "ConnectionDiagnostics")
                    .arg(Arg::new("transport", TsType::named("TransportConfig"))),
            )
            .command(
                Command::new("ai_generate_sql", "AiGenerateResult")
                    .arg(Arg::rust("connection_id", TsType::string()))
                    .arg(Arg::new("prompt", TsType::string()))
                    .arg(Arg::new("engine", TsType::named("DbEngine"))),
            )
            .command(
                Command::new("ai_explain_plan", "string")
                    .arg(Arg::new("plan", TsType::named("QueryPlanAnalysis"))),
            )
            .command(Command::new("ai_engine_status", "AiEngineStatus"))
            .command(
                Command::returning("ai_set_provider", TsType::void())
                    .arg(Arg::new("config", TsType::named("AiProviderConfig"))),
            )
            .command(Command::new("ai_get_provider", "AiProviderConfig"))
    }

    /// Locally (and through `npm run typegen`) this regenerates the committed
    /// bindings. Under `CI` it instead asserts they are up to date, turning a Rust
    /// type change without a regenerate into a failing build.
    #[test]
    fn export_typescript_bindings() {
        let rendered = bridge().render();
        let path = Path::new(GENERATED);
        let normalized = normalized_bindings(&rendered.contents);

        if std::env::var_os("CI").is_some() {
            let committed = fs::read_to_string(path).expect("read generated bindings");
            assert!(
                normalized == committed,
                "stale bindings: {GENERATED} differs after normalization — run `npm run typegen` and commit the result"
            );
        } else {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).expect("create generated bindings directory");
            }
            fs::write(path, normalized).expect("write generated bindings");
        }
    }
}

#[cfg(test)]
mod crypto_provider_tests {
    /// The db connectors and the extension store build reqwest clients, and
    /// reqwest is compiled without a default crypto provider, so its
    /// `default_rustls_crypto_provider()` is a `panic!` until one is installed.
    /// `Client::new()` panics on builder failure rather than returning an
    /// error, so losing the install would surface as a crash on the user's
    /// first connection attempt, not as a compile error. This test fails
    /// instead.
    #[test]
    fn client_construction_does_not_panic_without_a_provider() {
        super::install_crypto_provider();
        let client = reqwest::Client::builder().build();
        assert!(client.is_ok(), "reqwest client failed to build: {client:?}");
    }

    /// run() installs the provider on every launch, and irodori-generate
    /// installs its own, so a second install must be harmless.
    #[test]
    fn installing_the_provider_twice_is_harmless() {
        super::install_crypto_provider();
        super::install_crypto_provider();
        assert!(reqwest::Client::builder().build().is_ok());
    }
}
