#!/usr/bin/env bash
# Keep host-provided libraries out of the AppImage (#214).
#
# The release AppImage bundled `libwayland-client.so.0`. The host's Mesa
# `libEGL` then resolves against that bundled copy instead of the system one and
# `eglGetPlatformDisplay` fails, so the app aborts before a window appears:
#
#   Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
#
# It is on the upstream AppImage excludelist for exactly this reason — a
# library that talks to the running compositor cannot be shipped by the app.
# The `linuxdeploy` build the bundler downloads does not carry it in its
# compiled-in list, so it is deployed as an ordinary dependency.
#
# ## Why this hooks the appimage plugin rather than linuxdeploy itself
#
# `linuxdeploy --exclude-library` only suppresses libraries *it* is about to
# deploy; anything the GTK plugin has already copied into the AppDir stays.
# `linuxdeploy-plugin-appimage` is the last step — it turns the finished AppDir
# into the .AppImage — so removing the file there covers every path that could
# have put it in, and still happens before Tauri signs the artifact for the
# updater. (Repacking after the fact is not an option: it would invalidate that
# signature.)
#
# ## Usage
#
# Run once before `tauri build`. It replaces the cached plugin with a shim, so
# it is idempotent and survives a warm cache.
set -euo pipefail

cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/tauri"
plugin="$cache_dir/linuxdeploy-plugin-appimage.AppImage"
real="$cache_dir/linuxdeploy-plugin-appimage.real.AppImage"
plugin_url="https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage"

# Libraries the host must always provide. Extend deliberately: every entry here
# is a promise that the system copy is ABI-compatible with what we link against.
excluded_libs=(
  libwayland-client.so.0
)

mkdir -p "$cache_dir"

shim_marker="irodori-appimage-exclude-shim"

# A previous run already installed the shim; the real plugin is beside it.
if [ -f "$plugin" ] && grep -q "$shim_marker" "$plugin" 2>/dev/null; then
  echo "appimage-exclude: shim already installed"
else
  if [ -f "$plugin" ]; then
    mv "$plugin" "$real"
  elif [ ! -f "$real" ]; then
    echo "appimage-exclude: downloading linuxdeploy-plugin-appimage"
    curl -fL --retry 3 --retry-delay 2 -o "$real" "$plugin_url"
  fi
fi
chmod +x "$real"

{
  printf '#!/usr/bin/env bash\n'
  printf '# %s — generated by scripts/appimage-exclude-host-libs.sh (#214)\n' "$shim_marker"
  printf 'set -euo pipefail\n'
  printf 'real="$(dirname "$0")/%s"\n' "$(basename "$real")"
  printf '\n'
  printf '# The plugin takes the AppDir as --appdir; linuxdeploy also exports APPDIR.\n'
  printf 'appdir="${APPDIR:-}"\n'
  printf 'prev=""\n'
  printf 'for arg in "$@"; do\n'
  printf '  case "$prev" in --appdir) appdir="$arg" ;; esac\n'
  printf '  case "$arg" in --appdir=*) appdir="${arg#--appdir=}" ;; esac\n'
  printf '  prev="$arg"\n'
  printf 'done\n'
  printf '\n'
  printf 'if [ -n "$appdir" ] && [ -d "$appdir" ]; then\n'
  for lib in "${excluded_libs[@]}"; do
    printf '  find "$appdir" -name %q -type f -print -delete\n' "$lib"
  done
  printf 'else\n'
  printf '  echo "%s: no AppDir on the command line; nothing excluded" >&2\n' "$shim_marker"
  printf 'fi\n'
  printf '\n'
  printf 'exec "$real" "$@"\n'
} >"$plugin"

chmod +x "$plugin"
echo "appimage-exclude: shim installed at $plugin"
printf 'appimage-exclude: excluding %s\n' "${excluded_libs[*]}"
